name: "Quarto Render"
branding:
  icon: 'award'  
  color: 'blue'
description: "Renders a repo of documents with Quarto"
runs:
  using: "composite"
  steps: 
    - run: echo "The job was automatically trigged by a ${{ github.event_name }}"
    - name: "AHHHH"
      uses: quarto-dev/quarto-actions/install-quarto@v1
      run: |
        quarto render 

    - run: echo "The job was automatically trigged by a ${{ github.event_name }}"
