name: "Quarto Render"
branding:
  icon: 'award'  
  color: 'blue'
description: "Renders a repo of documents with Quarto"
runs:
  using: "composite"
  steps: 
    - name: "install quarto"
      uses: quarto-dev/quarto-actions/install-quarto@v1
    - run: |
        quarto render 
      shell: bash
