name: Simple freeze test
on: 
  push:
  pull_request:

jobs:
  simple-freeze-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests/freeze_test
    steps:
    - uses: actions/checkout@v2

    - name: "Check directory"
      run: |
        ls -l

    - name: "Install Quarto and render"
      uses: pommevilla/quarto-render@main

    - name: "Check directory"
      run: |
        echo "Listing root"
        ls -l

        echo "Listing site/*:"
        ls -l _site/*

        echo "Listing site/*/*:"
        ls -l _site/*/*
