name: Output format test
on: 
  push:
  pull_request:

jobs:
  output-format-test:
    runs-on: ubuntu-latest
    #defaults:
    #  run:
    #    working-directory: ./tests/output_format_test
    steps:
    - uses: actions/checkout@v2

    - name: "Install Quarto and render"
      uses: pommevilla/quarto-render@feature/render-to
      with:
        output_format: all
        target_directory: tests/output_format_test

    - name: "Check directory"
      run: |
        pwd
        ls -l

